### ISSUE TITLE
model evaluation

### ISSUE THREAD

**Issue by YeLuoSuiYou** [RoyZhao926/CatVersion#3]
I sincerely want to evaluate your model, how can I run it more simply

**Comment by RoyZhao926** [comment]
You can calculate the CLIP score using the evaluation method at https://github.com/rinongal/textual_inversion, hopefully this will help you!

**Comment by RoyZhao926** [comment]
You can calculate the CLIP score using the code in TI (https://github.com/rinongal/textual_inversion). Hopefully this will help you!

**Comment by RoyZhao926** [comment]
You can utilize the code in TI (https://github.com/rinongal/textual_inversion) to calculate the CLIP score. Hopefully this will help you!

**Comment by RoyZhao926** [comment]
You can utilize the code in TI (https://github.com/rinongal/textual_inversion) to calculate the CLIP score. Hopefully this will help you :)

**Comment by RoyZhao926** [comment]
You can reference the evaluation methods (or codes) in TI (https://github.com/rinongal/textual_inversion) or DreamBooth (https://github.com/google/dreambooth). Hopefully this will help you :)
