### ISSUE TITLE
Error in run.sh

### ISSUE THREAD

**Issue by wzic** [RoyZhao926/CatVersion#4]
Hi! Thanks for the great work. Got this error when running run.sh. Any way to solve it? Thanks!
<img width="765" alt="Snipaste_2024-02-25_19-33-27" src="https://github.com/RoyZhao926/CatVersion/assets/55567040/57216a31-f628-43d8-bd4c-16fd33338d35">

**Comment by RoyZhao926** [comment]
You seem to have imported Transformers from the conda environment. please use Transformers in the current directory, as we have modified some of its functions.

**Comment by wzic** [comment]
solved. thanks.
